apiVersion: v1
kind: Service
metadata:
  name: django-todo-nodeport
spec:
  type: NodePort
  selector:
    app: django-todo
  ports:
  - protocol: TCP
    targetPort: 8000
    Port: 8000
    nodePort: 30007
